CREATE TABLE active_tokens (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    token VARCHAR(32) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE dead_tokens (
    id INT AUTO_INCREMENT PRIMARY KEY,
    token VARCHAR(32) NOT NULL UNIQUE,
    invalidated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE order_list ADD COLUMN token VARCHAR(32);
ALTER TABLE item_list ADD COLUMN token VARCHAR(32);
